### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by FedericoCeratto** [rnentjes/nim-ludens#1]
Hi,

The build fails using csfml-2.3.0 and libcsfml-dev 2.2 on Debian:
.nimble/pkgs/ludens-0.1/screen.nim(20, 38) Error: undeclared identifier: 'TKeyCode'

**Comment by rnentjes** [comment]
This project was a bit outdated, I updated it to the latest nim version. 

Not sure if that fixes your problem, but please give it a go.

**Comment by FedericoCeratto** [comment]
Thank you for the quick reply! Same problem, unfortunately.

**Comment by rnentjes** [comment]
I did a quick check and installed nim and the libraries with nimble (opengl, sfml and ludens) on a fresh system and compiling the minimal.nim example with the following command line works for me:

nim c -d:useRealtimeGC minimal.nim

If you can show me your code I will take a look.

**Comment by FedericoCeratto** [comment]
The issue was due to sfml not being installed (only csfml was). Thank you!
